
spring:
  datasource:
    url: jdbc:mysql://120.78.153.88:3306/paul_test?characterEncoding=utf8&useSSL=true
    driverClassName: com.mysql.jdbc.Driver
    username:
    password:
  jpa:
    database: Mysql
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.improvedNamingStrategy


